# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('nickname', models.CharField(default='匿名用户', max_length=6, verbose_name='用户名')),
                ('birthday', models.DateField(default='1900-0-0', verbose_name='年龄')),
                ('sex', models.CharField(choices=[('man', '男'), ('featle', '女')], default='female', max_length=6, verbose_name='性别')),
                ('location', models.CharField(choices=[('北京', '北京'), ('南京', '南京'), ('上海', '上海'), ('安徽', '安徽')], default='火星', max_length=10, verbose_name='居住地')),
                ('avatars', models.CharField(max_length=256, verbose_name='头像')),
            ],
        ),
    ]
