# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_gender', models.CharField(choices=[('man', '男'), ('featle', '女')], default='male', max_length=6, verbose_name='匹配的性别')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('南京', '南京'), ('上海', '上海'), ('安徽', '安徽')], default='上海', max_length=15, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让未匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('nickname', models.CharField(default='匿名用户', max_length=6, verbose_name='用户名')),
                ('birthday', models.DateField(default='1900-01-01', verbose_name='年龄')),
                ('sex', models.CharField(choices=[('man', '男'), ('featle', '女')], default='female', max_length=6, verbose_name='性别')),
                ('location', models.CharField(choices=[('北京', '北京'), ('南京', '南京'), ('上海', '上海'), ('安徽', '安徽')], default='火星', max_length=10, verbose_name='居住地')),
                ('avatars', models.CharField(max_length=256, verbose_name='头像')),
            ],
        ),
    ]
